DROP TABLE Partido;
DROP TABLE Round;
DROP Table Liga;
DROP Table Equipo;

CREATE TABLE Equipo (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name varchar(255),
   PRIMARY KEY(id)
);

CREATE TABLE Liga (
  id varchar(255),
  name varchar(255),
  PRIMARY KEY (id)
);

CREATE TABLE Round (
  id varchar(255),
  liga_id varchar(255),
  r_number int,
   PRIMARY KEY (id),
CONSTRAINT FK_11 FOREIGN KEY (liga_id) REFERENCES liga (id)

);

CREATE TABLE Partido (
  round_id varchar(255),
  equipo_casa int,
  equipo_visita int,
  marcador_casa int,
  marcador_visita int,
  fecha DATE,
  PRIMARY KEY (round_id, equipo_casa, equipo_visita),
CONSTRAINT FK_21 FOREIGN KEY (round_id) REFERENCES Round (id),
CONSTRAINT FK_22 FOREIGN KEY (equipo_casa) REFERENCES Equipo (id),
CONSTRAINT FK_23 FOREIGN KEY (equipo_visita) REFERENCES Equipo (id)
);


DELETE FROM partido;
DELETE FROM ROUND;
DELETE FROM EQUIPO;
DELETE FROM LIGA;
